export const studentFormItems = [
  {
    label: 'First Name',
    id: 'firstName',
    name: 'firstName',
    type: 'text',
    placeholder: 'Enter first name',
    required: true,
  },
  {
    label: 'Last Name',
    id: 'lastName',
    name: 'lastName',
    type: 'text',
    placeholder: 'Enter last name',
    required: true,
  },
  {
    label: 'Email',
    id: 'email',
    name: 'email',
    type: 'email',
    placeholder: 'Enter email',
    required: true,
  },
  {
    label: 'Phone',
    id: 'phone',
    name: 'phone',
    type: 'text',
    placeholder: 'Enter phone',
    required: true,
  },
  {
    label: 'Website',
    id: 'website',
    name: 'website',
    type: 'text',
    placeholder: 'Enter website',
    required: true,
  },
  {
    label: 'Company Name',
    id: 'companyName',
    name: 'companyName',
    type: 'text',
    placeholder: 'Enter company name',
    required: true,
  },
];
